#!/bin/bash
mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE USER IF NOT EXISTS '$INIT_DB_USER'@'%' IDENTIFIED BY '$INIT_DB_PASS';
    GRANT SELECT, INSERT, UPDATE ON company_db.* TO '$INIT_DB_USER'@'%';
    FLUSH PRIVILEGES;
EOSQL