server {
    listen 80;
    server_name 100.96.177.104;

    location / {
        proxy_pass http://100.74.182.127:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
