CREATE DATABASE IF NOT EXISTS mmh_project;
USE mmh_project;

CREATE TABLE IF NOT EXISTS keys_storage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_tag VARCHAR(255) UNIQUE NOT NULL,
    encrypted_dek TEXT NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    enc_cccd TEXT NOT NULL,
    enc_phone TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE USER IF NOT EXISTS 'backend_user'@'100.74.182.127' IDENTIFIED BY 'MatMaHoc2026@';
GRANT SELECT, INSERT, UPDATE ON mmh_project.* TO 'backend_user'@'100.74.182.127';
FLUSH PRIVILEGES;
