events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name 100.96.177.104; 

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;
        ssl_protocols TLSv1.3;
        ssl_verify_client on;
        ssl_client_certificate /etc/nginx/certs/ca.crt;

        location / {
            proxy_set_header X-Client-Cert-Hash $ssl_client_fingerprint;
            proxy_pass http://100.74.182.127:8000; # IP Node 2
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
